gui:
  showFileTree: false
git:
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --'
  pagers:
    - pager: delta --dark --syntax-theme='Solarized (dark)' --paging=never
      colorArg: always 
os:
  editPreset: 'nvim'
promptToReturnFromSubprocess: false
customCommands:
  - key: 'C'
    command: 'git cz commit'
    context: 'files'
    loadingText: 'opening git-cz commit tool'
    output: terminal
